window.cashmusic=function(){var h;null!=window.cashmusic?h=window.cashmusic:(h={embeds:[],loaded:!1,soundplayer:!1,lightbox:!1,options:"",path:"",templates:{},_init:function(){var a=window.cashmusic;a.scriptElement=document.querySelector('script[src$="cashmusic.js"]');a.scriptElement&&(a.path=a.scriptElement.src.substr(0,a.scriptElement.src.length-12));a.options=String(a.scriptElement.getAttribute("data-options"));"function"!==typeof JSON.parse&&a.loadScript(a.path+"lib/json_parse.js");-1!==this.options.indexOf("lightboxvideo")&&
a.loadScript(a.path+"lightbox/lightbox.js");0<document.querySelectorAll("a.cashmusic.soundplayer,div.cashmusic.soundplayer").length&&a.loadScript(a.path+"soundplayer/soundplayer.js");this.loaded=!0},contentLoaded:function(a){var b=!1,c=!0,d=window.document,e=d.documentElement,f=function(c){if(!("readystatechange"==c.type&&"complete"!=d.readyState)&&(h.events.remove("load"==c.type?window:d,c.type,f),!b&&(b=!0)))a.call(window,c.type||c)},g=function(){try{e.doScroll("left")}catch(a){setTimeout(g,50);
return}f("poll")};if("complete"==d.readyState)a.call(window,"lazy");else{if(d.createEventObject&&e.doScroll){try{c=!window.frameElement}catch(m){}c&&g()}this.events.add(d,"DOMContentLoaded",f);this.events.add(d,"readystatechange",f);this.events.add(d,"load",f)}},embed:function(a,b,c,d,e,f){var g=window.cashmusic,h=a.replace(/\/$/,"")+"/request/embed/"+b+"/location/"+encodeURIComponent(window.location.href.replace(/\//g,"!slash!")),k=document.createElement("iframe");k.src=h;k.style.width="100%";k.style.border=
"0";k.style.overflow="hidden";if(e)var l=document.querySelector(e);else a=document.querySelectorAll('script[src$="cashmusic.js"],script.cashmusic'),l=a[a.length-1];if(l){if(c){var j=document.createElement("span");j.className="cashmusic_embed";j.style.position="relative";g.contentLoaded(function(){d||(d="open element");g.overlay.create(function(){var a=document.createElement("a");a.href=h;a.target="_blank";a.innerHTML=d;j.appendChild(a);l.parentNode.insertBefore(j,l);var b=f;"object"!==typeof b&&(b=
{top:"40px",left:"30%",width:"40%",marginLeft:"0"});g.events.add(a,"click",function(a){g.overlay.resize(b.top,b.left,b.width,b.marginLeft);g.overlay.content.appendChild(k);window.cashmusic.fader.init(g.overlay.bg,100);a.preventDefault();return!1})})})}else j=document.createElement("div"),j.className="cashmusic_embed",j.style.position="relative",j.appendChild(k),l.parentNode.insertBefore(j,l);g.embeds.push({el:k,id:b});1===g.embeds.length&&g.events.add(window,"message",function(a){if("cashmusic_embed"==
a.data.substring(0,15)){a=a.data.split("_");for(var b=0;b<g.embeds.length;b++)g.embeds[b].id==a[2]&&(g.embeds[b].el.height=a[3],g.embeds[b].el.style.height=a[3]+"px")}})}},getJSON:function(a){return"function"===typeof JSON.parse?JSON.parse(a):json_parse(a)},getTemplate:function(a,b){var c=window.cashmusic,d=c.templates;void 0!==d[a]?b(d[a]):(this.ajax.send(c.path+"templates/"+a+".html",!1,function(c){d[a]=c;b(c)}),this.ajax.send(c.path+"templates/"+a+".css",!1,function(a){c.styles.injectCSS(a)}))},
loadScript:function(a,b){if(0<document.querySelectorAll('a[src="'+a+'"]').length)"function"===typeof b&&b();else{var c=document.getElementsByTagName("head")[0]||document.documentElement,d=document.createElement("script");d.src=a;var e=!1;d.onload=d.onreadystatechange=function(){if(!e&&(!this.readyState||"loaded"===this.readyState||"complete"===this.readyState))e=!0,"function"===typeof b&&b(),d.onload=d.onreadystatechange=null,c&&d.parentNode&&c.removeChild(d)};c.insertBefore(d,c.firstChild)}},ajax:{getXHR:function(){try{return new XMLHttpRequest}catch(a){try{return new ActiveXObject("Msxml2.XMLHTTP")}catch(b){try{return new ActiveXObject("Microsoft.XMLHTTP")}catch(c){return!1}}}},
send:function(a,b,c,d){var e="POST";b||(e="GET",b=null);var f=this.getXHR();f&&(f.open(e,a,!0),f.setRequestHeader("X-Requested-With","XMLHttpRequest"),"POST"==e&&f.setRequestHeader("Content-type","application/x-www-form-urlencoded"),"function"==typeof c&&(f.onreadystatechange=function(){4===f.readyState&&(200===f.status?c(f.responseText):"function"===typeof d&&d(f.responseText))}),f.send(b))},jsonp:function(a){var b=document.createElement("script");b.src=a;document.getElementsByTagName("head")[0].appendChild(b)},
encodeForm:function(a){if("object"!==typeof a)return!1;var b="";a=a.elements||a;for(var c=0;c<a.length;c++)"checkbox"===a[c].type||"radio"===a[c].type?a[c].checked&&(b+=(b.length?"&":"")+a[c].name+"="+a[c].value):b+=(b.length?"&":"")+a[c].name+"="+a[c].value;return encodeURI(b)}},events:{add:function(a,b,c){a.attachEvent?(a["e"+b+c]=c,a[b+c]=function(){a["e"+b+c](window.event)},a.attachEvent("on"+b,a[b+c])):a.addEventListener(b,c,!1)},remove:function(a,b,c){a.detachEvent?(a.detachEvent("on"+b,a[b+
c]),a[b+c]=null):a.removeEventListener(b,c,!1)},fire:function(a,b,c){if(document.dispatchEvent){var d=new CustomEvent(b,!0,!0,{detail:c});a.dispatchEvent(d)}else d=document.createEventObject(),d.detail=c,a.fireEvent("on"+b,d)}},fader:{elem:!1,flag:!1,alpha:!1,target:!1,init:function(a,b,c){var d=window.cashmusic.fader;d.setElement(a);clearInterval(d.si);d.alpha=d.elem.style.opacity?100*parseFloat(d.elem.style.opacity):0;d.flag=d.alpha>b?-1:1;d.target=b;0==d.alpha&&0<b&&(d.elem.style.opacity=0,d.elem.style.display=
"block");d.si=setInterval(function(){d.tween(c)},10)},tween:function(a){var b=window.cashmusic.fader;b.alpha==b.target?(clearInterval(b.si),"function"==typeof a&&a()):(a=Math.round(b.alpha+0.05*(b.target-b.alpha))+b.flag,b.elem.style.opacity=a/100,b.elem.style.filter="alpha(opacity="+a+")",0==a&&(b.elem.style.display="none"),b.alpha=a)},hide:function(a){var b=window.cashmusic.fader;b.setElement(a);b.elem.style.opacity=0;b.elem.style.display="none"},show:function(a){var b=window.cashmusic.fader;b.setElement(a);
b.elem.style.opacity=100;b.elem.style.display="block"},setElement:function(a){window.cashmusic.fader.elem="string"===typeof a?document.getElementById(a):a}},measure:{viewport:function(){return{x:document.body.offsetWidth||window.innerWidth||0,y:document.body.offsetHeight||window.innerHeight||0}}},overlay:{bg:!1,content:!1,total:0,callbacks:[],create:function(a){var b=window.cashmusic,c=b.overlay;!1===c.bg?(c.total++,"function"===typeof a&&c.callbacks.push(a),1==c.total&&b.getTemplate("overlay",function(a){var e=
document.createElement("div");e.innerHTML=a;c.bg=e.firstChild;c.bg.style.display="none";document.body.appendChild(c.bg);e=null;a=c.bg.getElementsByTagName("div");c.content=a[0];b.events.add(window,"keyup",function(a){27==a.keyCode&&(c.bg.style.display="block",b.fader.hide(c.bg),c.content.innerHTML="")});b.events.add(c.bg,"click",function(a){a.target===this&&(b.fader.hide(c.bg),c.content.innerHTML="")});for(a=0;a<c.callbacks.length;a++)c.callbacks[a]()})):a()},resize:function(a,b,c,d){var e=window.cashmusic.overlay.content.style;
e.top=a;e.left=b;e.width=c;e.marginLeft=d}},styles:{addClass:function(a,b){a.className=a.className+" "+b},hasClass:function(a,b){return-1<(" "+a.className+" ").indexOf(" "+b+" ")},injectCSS:function(a){var b=document.getElementsByTagName("head")[0]||document.documentElement,c=document.createElement("style");c.type="text/css";c.innerHTML=a;b.insertBefore(c,b.firstChild)},swapClasses:function(a,b,c){a.className=(" "+a.className+" ").replace(" "+b+" "," "+c+" ").replace(/^\s+/,"").replace(/\s+$/,"")}}},
h.contentLoaded(function(){h._init(h)}));return h}();