(function(){var c=window.cashmusic;c.stripe={eventAttached:!1,getYears:function(){for(var c=(new Date).getFullYear(),g={},d=0;20>d;d++)g[c]=c,c++;return g},generateToken:function(c,g){var d=window.cashmusic;d.embedded?d.events.fire(d,"stripetokenrequested",params):d.loadScript("https://js.stripe.com/v2/",function(){var a=[];a.push({id:"name",type:"text",placeholder:"Cardholder name"});a.push({id:"email",type:"email",placeholder:"Email address"});a.push({id:"card-number",type:"text",placeholder:"Credit card number"});
a.push({id:"card-expiry-month",type:"select",options:{"01":"01: Jan","02":"02: Feb","03":"03: Mar","04":"04: Apr","05":"05: May","06":"06: Jun","07":"07: Jul","08":"08: Aug","09":"09: Sep",10:"10: Oct",11:"11: Nov",12:"12: Dec"},value:"01"});a.push({id:"card-expiry-year",type:"select",options:d.stripe.getYears(),placeholder:(new Date).getFullYear()});a.push({id:"card-cvc",type:"text",placeholder:"CVV"});a.push({id:"stripe-submit",type:"submit",text:"Submit Payment"});d.userinput.getInput(a,"getstripetoken",
null,"");d.stripe.eventAttached||(d.events.add(d,"userinput",function(a){"getstripetoken"==a.detail["cm-userinput-type"]&&(Stripe.setPublishableKey(c),Stripe.card.createToken({name:a.detail.name,number:a.detail["card-number"],cvc:a.detail["card-cvc"],exp_month:a.detail["card-expiry-month"],exp_year:a.detail["card-expiry-year"]},function(c,e,f){e.error?(document.getElementById("cm-userinput-message").innerHTML=e.error.message,d.styles.addClass(document.getElementsByClassName("cm-userinput-container")[0],
"nope"),setTimeout(function(){d.styles.removeClass(document.getElementsByClassName("cm-userinput-container")[0],"nope")},800)):(d.storage.checkoutdata.stripe=e.id,d.storage.checkoutdata.name=a.detail.name,d.storage.checkoutdata.email=a.detail.email,d.events.fire(d,"checkoutdata",d.storage.checkoutdata,g),d.overlay.reveal('<div class="cm-loading"></div>'))}))}),d.stripe.eventAttached=!0)})}};c.userinput={getInput:function(e,g,d,a){g=g||"unknown";var h=document.createElement("form"),m=document.createElement("div");
m.className="cm-userinput-container";var n=document.createElement("div");n.id="cm-userinput-message";n.innerHTML="&nbsp;";a&&(n.innerHTML=a);h.className="cm-userinput "+g+" "+d;e.push({id:"cm-userinput-type",type:"hidden",value:g});for(d=0;d<e.length;d++){var f=e[d];if("submit"!==f.type&&"select"!==f.type)a=document.createElement("input"),a.type=f.type,a.placeholder=f.placeholder,f.value&&(a.value=f.value);else if("select"==f.type){a=document.createElement("select");var k=Object.keys(f.options);k.sort(function(c,
a){return c-a});for(var l=0;l<k.length;l++){var p=document.createElement("option");p.value=k[l];p.text=f.options[k[l]];f.value==k[l]&&(p.selected="selected");a.appendChild(p)}}else a=document.createElement("button"),a.type="submit",a.innerHTML=f.text;a.name=f.id;a.id="cm-userinput-"+g+"-"+f.id;f.required&&a.setAttribute("data-required","1");"stripe-submit"==f.id&&c.storage.checkoutdata.total&&(f=document.createElement("div"),f.id="cm-amount-message",f.innerHTML='<h2 class="cm-pricing">Transaction amount: <span>'+
b.storage.checkoutdata.total+"</span></h2>\x3c!--cm-pricing--\x3e",h.appendChild(f));h.appendChild(a)}m.appendChild(n);m.appendChild(h);c.events.add(h,"submit",function(a){a.preventDefault();a.stopPropagation();for(var d={},e=!1,f=0;f<h.elements.length;f++)a=h.elements[f],d[a.name]=a.value,a.getAttribute("data-required")&&""==a.value?(e=!0,c.styles.addClass(a,"incomplete")):c.styles.removeClass(a,"incomplete");e?(document.getElementById("cm-userinput-message").innerHTML="Please complete all required fields.",
c.styles.addClass(document.getElementsByClassName("cm-userinput-container")[0],"nope"),setTimeout(function(){c.styles.removeClass(document.getElementsByClassName("cm-userinput-container")[0],"nope")},800)):c.events.fire(c,"userinput",d)});c.overlay.reveal(m)}};c.checkout={prepped:!1,countries:{AF:"Afghanistan",AX:"\u00c5land Islands",AL:"Albania",DZ:"Algeria",AS:"American Samoa",AD:"Andorra",AO:"Angola",AI:"Anguilla",AQ:"Antarctica",AG:"Antigua and Barbuda",AR:"Argentina",AM:"Armenia",AW:"Aruba",
AU:"Australia",AT:"Austria",AZ:"Azerbaijan",BS:"Bahamas",BH:"Bahrain",BD:"Bangladesh",BB:"Barbados",BY:"Belarus",BE:"Belgium",BZ:"Belize",BJ:"Benin",BM:"Bermuda",BT:"Bhutan",BO:"Bolivia",BQ:"Bonaire, Saint Eustatius and Saba",BA:"Bosnia-Herzegovina",BW:"Botswana",BV:"Bouvet Island",BR:"Brazil",IO:"British Indian Ocean Territory",BN:"Brunei Darussalam",BG:"Bulgaria",BF:"Burkina Faso",BI:"Burundi",KH:"Cambodia",CM:"Cameroon",CA:"Canada",CV:"Cape Verde",KY:"Cayman Islands",CF:"Central African Republic",
TD:"Chad",CL:"Chile",CN:"China",CX:"Christmas Island",CC:"Cocos (Keeling) Islands",CO:"Colombia",KM:"Comoros",CG:"Congo",CD:"Congo, the Democratic Republic of the",CK:"Cook Islands",CR:"Costa Rica",CI:"C\u00f4te d\u2019Ivoire",HR:"Croatia",CU:"Cuba",CW:"Curacao",CY:"Cyprus",CZ:"Czech Republic",DK:"Denmark",DJ:"Djibouti",DM:"Dominica",DO:"Dominican Republic",EC:"Ecuador",EG:"Egypt",SV:"El Salvador",GQ:"Equatorial Guinea",ER:"Eritrea",EE:"Estonia",ET:"Ethiopia",FK:"Falkland Islands",FO:"Faroe Islands",
FJ:"Fiji",FI:"Finland",FR:"France",GF:"French Guiana",PF:"French Polynesia",TF:"French Southern Territories",GA:"Gabon",GM:"Gambia",GE:"Georgia",DE:"Germany",GH:"Ghana",GI:"Gibraltar",GR:"Greece",GL:"Greenland",GD:"Grenada",GP:"Guadeloupe",GU:"Guam",GT:"Guatemala",GG:"Guernsey",GN:"Guinea",GW:"Guinea-Bissau",GY:"Guyana",HT:"Haiti",HM:"Heard Island and McDonald Islands",VA:"Holy See (Vatican City State)",HN:"Honduras",HK:"Hong Kong",HU:"Hungary",IS:"Iceland",IN:"India",ID:"Indonesia",IR:"Iran, Islamic Republic of",
IQ:"Iraq",IE:"Ireland",IM:"Isle of Man",IL:"Israel",IT:"Italy",JM:"Jamaica",JP:"Japan",JE:"Jersey",JO:"Jordan",KZ:"Kazakhstan",KE:"Kenya",KI:"Kiribati",KP:"North Korea",KR:"Korea",KW:"Kuwait",KG:"Kyrgyzstan",LA:"Lao People\u2019s Democratic Republic",LV:"Latvia",LB:"Lebanon",LS:"Lesotho",LR:"Liberia",LY:"Libyan Arab Jamahiriya",LI:"Liechtenstein",LT:"Lithuania",LU:"Luxembourg",MO:"Macao",MK:"Macedonia, the former Yugoslav Republic of",MG:"Madagascar",MW:"Malawi",MY:"Malaysia",MV:"Maldives",ML:"Mali",
MT:"Malta",MH:"Marshall Islands",MQ:"Martinique",MR:"Mauritania",MU:"Mauritius",YT:"Mayotte",MX:"Mexico",FM:"Micronesia, Federated States of",MD:"Moldova, Republic of",MC:"Monaco",MN:"Mongolia",ME:"Montenegro",MS:"Montserrat",MA:"Morocco",MZ:"Mozambique",MM:"Myanmar",NA:"Namibia",NR:"Nauru",NP:"Nepal",NL:"Netherlands",NC:"New Caledonia",NZ:"New Zealand",NI:"Nicaragua",NE:"Niger",NG:"Nigeria",NU:"Niue",NF:"Norfolk Island",MP:"Northern Mariana Islands",NO:"Norway",OM:"Oman",PK:"Pakistan",PW:"Palau",
PS:"Palestinian Territory, Occupied",PA:"Panama",PG:"Papua New Guinea",PY:"Paraguay",PE:"Peru",PH:"Philippines",PN:"Pitcairn",PL:"Poland",PT:"Portugal",PR:"Puerto Rico",QA:"Qatar",RE:"R\u00e9union",RO:"Romania",RU:"Russian Federation",RW:"Rwanda",BL:"Saint Barth\u00e9lemy",SH:"Saint Helena, Ascension and Tristan da Cunha",KN:"Saint Kitts and Nevis",LC:"Saint Lucia",MF:"Saint Martin (French part)",PM:"Saint Pierre and Miquelon",VC:"Saint Vincent and the Grenadines",WS:"Samoa",SM:"San Marino",ST:"Sao Tome and Principe",
SA:"Saudi Arabia",SN:"Senegal",RS:"Serbia",SC:"Seychelles",SL:"Sierra Leone",SG:"Singapore",SX:"Sint Maarten (Dutch part)",SK:"Slovakia",SI:"Slovenia",SB:"Solomon Islands",SO:"Somalia",ZA:"South Africa",GS:"South Georgia and the South Sandwich Islands",ES:"Spain",LK:"Sri Lanka",SD:"Sudan",SR:"Suriname",SJ:"Svalbard and Jan Mayen",SZ:"Swaziland",SE:"Sweden",CH:"Switzerland",SY:"Syrian Arab Republic",TW:"Taiwan, Province of China",TJ:"Tajikistan",TZ:"Tanzania, United Republic of",TH:"Thailand",TL:"Timor-Leste",
TG:"Togo",TK:"Tokelau",TO:"Tonga",TT:"Trinidad and Tobago",TN:"Tunisia",TR:"Turkey",TM:"Turkmenistan",TC:"Turks and Caicos Islands",TV:"Tuvalu",UG:"Uganda",UA:"Ukraine",AE:"United Arab Emirates",GB:"United Kingdom",US:"United States",UY:"Uruguay",UZ:"Uzbekistan",VU:"Vanuatu",VE:"Venezuela, Bolivarian Republic of",VN:"Viet Nam",VG:"Virgin Islands, British",VI:"Virgin Islands, U.S.",WF:"Wallis and Futuna",EH:"Western Sahara",YE:"Yemen",ZM:"Zambia",ZW:"Zimbabwe"},prep:function(){c.checkout.prepped||
(c.styles.injectCSS(c.path+"/templates/checkout.css",!1,!0),c.checkout.prepped=!0)},begin:function(e,g){if(c.embedded)c.events.fire(c,"begincheckout",e);else if(c.checkout.prep(),c.storage.checkoutdata={stripe:!1,paypal:!1,shipping:!1,currency:!1,name:!1,email:!1,recurring:!1,origin:window.location.href,total:!1},"https:"!==location.protocol&&!0!==e.testing&&(e.stripe=!1),e.recurring&&(c.storage.checkoutdata.recurring=!0),e.total&&(c.storage.checkoutdata.total=e.total),e.shipping){var d=[];d.push({id:"name",
type:"text",placeholder:"Ship to name",required:!0},{id:"address1",type:"text",placeholder:"Shipping address 1",required:!0},{id:"address2",type:"text",placeholder:"Shipping address 2"},{id:"city",type:"text",placeholder:"City",required:!0},{id:"state",type:"text",placeholder:"State/Province/Region",required:!0},{id:"postalcode",type:"text",placeholder:"Postal code",required:!0});if(e.stripe||e.paypal){var a="US";if(e.currency)switch(e.currency){case "GBP":a="GB";break;case "AUD":a="AU";break;case "JPY":a=
"JP";break;case "CAD":a="CA";break;case "NZD":a="NZ";break;case "HKD":a="HK";break;case "MXN":a="MX";break;case "NOK":a="NO"}d.push({id:"country",type:"select",options:c.checkout.countries,value:a});e.recurring||"object"===typeof e.shipping&&d.push({id:"shipping-region",type:"select",options:{"":"Select shipping region",r1:e.shipping.r1,r2:e.shipping.r2},required:!0});d.push({id:"shipping-submit",type:"submit",text:"Set shipping info"});"object"===typeof e.shipping?c.userinput.getInput(d,"getshippingaddress",
"shipping"):c.userinput.getInput(d,"getshippingaddress","noshipping");c.events.add(c,"userinput",function(a){"getshippingaddress"==a.detail["cm-userinput-type"]&&(c.storage.checkoutdata.shipping=a.detail,c.checkout.initiatepayment(e,g))})}else c.checkout.showerror()}else c.checkout.initiatepayment(e,g)},initiatepayment:function(e,g){if(e.stripe&&!e.paypal)c.stripe.generateToken(e.stripe,g);else if(!e.stripe&&e.paypal)c.storage.checkoutdata.paypal=!0,c.events.fire(c,"checkoutdata",c.storage.checkoutdata,
g),c.overlay.reveal('<div class="cm-loading"></div>');else if(e.stripe&&e.paypal){var d=document.createElement("div");d.className="cm-checkout-choose";var a=document.createElement("span"),h=document.createElement("span");a.innerHTML="Pay with PayPal";a.className="pay-pp";h.innerHTML="Pay with a credit card";h.className="pay-cc";c.events.add(a,"click",function(a){a.preventDefault();a.stopPropagation();c.storage.checkoutdata.paypal=!0;c.events.fire(c,"checkoutdata",c.storage.checkoutdata,g);c.overlay.reveal('<div class="cm-loading"></div>')});
c.events.add(h,"click",function(a){a.preventDefault();a.stopPropagation();c.stripe.generateToken(e.stripe,g)});d.appendChild(a);d.appendChild(h);c.overlay.reveal(d)}else c.checkout.showerror()},showerror:function(e){c.overlay.reveal('<div class="cm-checkout-error">There are no valid payment types. Please add a payment connection. Check to make sure your site supports SSL (https) if you are using Stripe.</div>')}}})();
