(function(){var f=window.cashmusic;f.measure.getClickPosition=function(a){var b=a.currentTarget?a.currentTarget:a.srcElement,c=f.measure.getPosition(b),d=a.clientX-c.x;return{x:d,y:a.clientY-c.y,percentage:d/b.clientWidth}};f.measure.getPosition=function(a){for(var b=0,c=0;a;)b+=a.offsetLeft-a.scrollLeft+a.clientLeft,c+=a.offsetTop-a.scrollTop+a.clientTop,a=a.offsetParent;return{x:b,y:c}};Array.prototype.indexOf||(Array.prototype.indexOf=function(a){for(var b=0;b<this.length;b++)if(this[b]===a)return b;
return-1});f.soundplayer={playlist:!1,playlists:{},sound:!1,_init:function(){var a=f.soundplayer,b=document.querySelectorAll("div.cashmusic.soundplayer.playlist"),c=b.length;if(0<c)for(var d=0;d<c;d++){var e=b[d],g=f.getJSON(e.getAttribute("data-playlist")),g=a._formatPlaylist(g,e.id,d);e.id=e.id?e.id:g.id;for(var j=document.querySelectorAll("#"+e.id+' a[href$=".mp3"],#'+e.id+' a[href$=".MP3"],#'+e.id+' a[href$=".ogg"],#'+e.id+' a[href$=".OGG"],#'+e.id+' a[href$=".m4a"],#'+e.id+' a[href$=".M4A"],#'+
e.id+' a[href$=".wav"],#'+e.id+' a[href$=".WAV"]'),l=j.length,k=0;k<l;k++){var m=j[k];g.tracks.push(a._formatTrack(m,g.id));m.parentNode.removeChild(m)}j="<ol>";l=g.tracks.length;for(k=0;k<l;k++)g._index.push(g.tracks[k].id),soundManager.createSound({id:g.tracks[k].id,url:g.tracks[k].url}),j+='<li class="cashmusic soundplayer changetrack" data-track="'+(k+1)+'">'+g.tracks[k].title+"</li>";j+="</ol>";a.playlists[g.id]=g;(function(b,c,d){f.getTemplate("soundplayer",function(e){e=e.replace(/data-playerid=\"/g,
'data-playerid="'+c.id);e=e.replace(/onPlayer\":\"/g,'onPlayer":"'+c.id);b.innerHTML=e;b.style.visibility="visible";b.style.display="block";b.style.position="relative";e=document.querySelectorAll("#"+b.id+" div.cashmusic.soundplayer.playlist.tracklist");"undefined"!==e[0]&&(e[0].innerHTML=d);var g=document.querySelectorAll("#"+b.id+" div.cashmusic.soundplayer.playlist.nowplaying, #"+b.id+" div.cashmusic.soundplayer.playlist.playtime, #"+b.id+" div.cashmusic.soundplayer.playlist.toggletracklist");
e=g.length;for(var j=0;j<e;j++)g[j].innerHTML=g[j].getAttribute("data-content")+"";g=document.querySelectorAll("#"+b.id+" div.cashmusic.soundplayer.playlist.controls *, #"+b.id+" div.cashmusic.soundplayer.playlist.toggletracklist, #"+b.id+" li.cashmusic.soundplayer.changetrack");e=g.length;for(j=0;j<e;j++){var h=g[j];f.styles.hasClass(h,"playpause")&&(f.styles.addClass(h,"paused"),f.events.add(h,"click",function(){a.togglePlaylist(c.id)}));f.styles.hasClass(h,"nexttrack")&&f.events.add(h,"click",
function(){a.next(c.id,!0)});f.styles.hasClass(h,"prevtrack")&&f.events.add(h,"click",function(){a.previous(c.id)});f.styles.hasClass(h,"toggletracklist")&&f.events.add(h,"click",function(){var a=document.querySelectorAll("#"+b.id+" div.cashmusic.soundplayer.playlist.tracklist")[0].style;"undefined"!==a&&(a.height="auto"!==a.height?"auto":"1px");h.blur()});f.styles.hasClass(h,"changetrack")&&f.events.add(h,"click",function(b){b=(b.currentTarget?b.currentTarget:b.srcElement).getAttribute("data-track");
a.playlistPlayTrack(c.id,b)})}g=document.querySelectorAll("#"+b.id+" div.cashmusic.soundplayer.playlist.seekbar");e=g.length;for(j=0;j<e;j++)f.events.add(g[j],"click",function(b){a.seek(f.measure.getClickPosition(b).percentage,c.id)})})})(e,g,j)}var b=document.querySelectorAll("*.cashmusic.soundplayer.playstop,a.cashmusic.soundplayer.inline"),c=b.length;if(0<c){f.styles.injectCSS('a.cashmusic.soundplayer.inline.stopped:after{content: " [\u25b8]";}a.cashmusic.soundplayer.inline.playing:after{content: " [\u25aa]";}');
for(d=0;d<c;d++){var h=b[d];f.styles.addClass(h,"stopped");f.styles.hasClass(h,"playstop")||soundManager.createSound({id:h.href,url:h.href});f.events.add(h,"click",function(b){var c=f.styles.hasClass(h,"playstop")?soundManager.getSoundById(h.getAttribute("data-soundid")):soundManager.getSoundById(h.href);if(c)return a.toggle(c.id,!0),b.returnValue=!1,b.preventDefault&&b.preventDefault(),!1})}}b=document.querySelectorAll("*.cashmusic.soundplayer.playpause");c=b.length;if(0<c)for(d=0;d<c;d++)e=b[d],
f.styles.addClass(e,"paused"),e.getAttribute("data-soundid"),e.getAttribute("data-playerid")?f.events.add(e,"click",function(b){a.togglePlaylist((b.currentTarget?b.currentTarget:b.srcElement).getAttribute("data-playerid"));b.returnValue=!1;b.preventDefault&&b.preventDefault();return!1}):f.events.add(e,"click",function(b){a.toggle((b.currentTarget?b.currentTarget:b.srcElement).getAttribute("data-soundid"));b.returnValue=!1;b.preventDefault&&b.preventDefault();return!1})}};window.SM2_DEFER=!0;f.loadScript(f.path+
"lib/soundmanager/soundmanager2.js",function(){var a=f.soundplayer;window.soundManager=new SoundManager;soundManager.setup({url:f.path+"lib/soundmanager/swf/",flashVersion:9,flashLoadTimeout:7500,flashPollingInterval:30,html5PollingInterval:30,useHighPerformance:!0,onready:function(){a._init()},defaultOptions:{onload:function(){a._doLoad({id:this.id})},onstop:function(){a._doStop({id:this.id})},onfinish:function(){a._doFinish({id:this.id})},onpause:function(){a._doPause({id:this.id})},onplay:function(){a._doPlay({id:this.id})},
onresume:function(){a._doResume({id:this.id})},stream:!0,usePolicyFile:!0,volume:100,whileloading:function(){a._doLoading({id:this.id,loaded:this.bytesLoaded,total:this.bytesTotal,percentage:Math.round(1E3*(this.bytesLoaded/this.bytesTotal))/10})},whileplaying:function(){var b=Math.round(1E4*(this.position/this.duration))/100;a._doPlaying({id:this.id,position:this.position,duration:this.duration,percentage:b})}}});soundManager.beginDelayedInit();a._doFinish=function(){var b=document.querySelectorAll("*.cashmusic.setstyles");
a._updateStyles(b,"finish");a.next()};a._doLoad=function(){var b=document.querySelectorAll("*.cashmusic.setstyles");a._updateStyles(b,"load")};a._doLoading=function(b){var c=document.querySelectorAll("*.cashmusic.tween");a._updateTweens(c,"load",b.percentage)};a._doPause=function(){a._switchStylesForCollection(document.querySelectorAll("*.cashmusic.playpause"),"playing","paused");var b=document.querySelectorAll("*.cashmusic.setstyles");a._updateStyles(b,"pause")};a._doPlay=function(b){a._doResume(b)};
a._doPlaying=function(b){var c=document.querySelectorAll("*.cashmusic.tween");a._updateTweens(c,"play",b.percentage);a._updateTimes(b.percentage)};a._doResume=function(){for(var b=document.querySelectorAll('a.cashmusic.soundplayer.inline[href="'+a.sound.id+'"]'),c=b.length,d=0;d<c;d++)f.styles.swapClasses(b[d],"stopped","playing");a._switchStylesForCollection(document.querySelectorAll("*.cashmusic.playpause"),"paused","playing");b=document.querySelectorAll("*.cashmusic.setstyles");0<a.sound.position?
a._updateStyles(b,"play"):a._updateStyles(b,"resume")};a._doStop=function(b){b=document.querySelectorAll('a.cashmusic.soundplayer.inline[href="'+b+'"]');for(var c=b.length,d=0;d<c;d++)f.styles.swapClasses(b[d],"playing","stopped");b=document.querySelectorAll("*.cashmusic.setstyles");a._updateStyles(b,"stop")};a.pause=function(){a.sound&&a.sound.pause()};a.play=function(){a.sound&&a.sound.play()};a.resume=function(){a.sound&&a.sound.paused&&a.sound.resume()};a.seek=function(b,c){if(c){if(a.playlist){if(c!==
a.playlist.id)return!1}else return!1;a.sound.setPosition(Math.floor(b*a.sound.duration))}};a.stop=function(){a.sound&&(a.pause(),a.sound.setPosition(0),a._doStop(a.sound.id))};a.toggle=function(b,c){var d=c?a.stop:a.pause;a.sound=a.sound?a.sound:soundManager.getSoundById(b);a.sound.id!==b&&(d(),a.sound=soundManager.getSoundById(b));c&&!a.sound.paused&&0!=a.sound.playState?a.stop():a.sound.togglePause();a._updateTitle()};a.next=function(b,c){a.loadPlaylist(b);var d=!1,e=!1,g=a.playlist;g&&(g.current<
g.tracks.length?(d=parseInt(g.current)+1,e=!0):(d=1,c&&(e=!0)),g.current=d);e&&a.playlistPlayTrack(g.id,d)};a.previous=function(b){a.loadPlaylist(b);b=!1;var c=a.playlist;c&&(b=1<c.current?parseInt(c.current)-1:c.tracks.length,c.current=b,a.playlistPlayTrack(c.id,b))};a.togglePlaylist=function(b){a.loadPlaylist(b);a.toggle(a.playlist.tracks[a.playlist.current-1].id)};a.playlistPlayTrack=function(b,c){a.loadPlaylist(b);a.stop();a.playlist.current=c;a.toggle(a.playlist.tracks[c-1].id)};a.loadPlaylist=
function(b){a.sound&&a.playlist&&a.playlist.id!=b&&a.pause();a.sound&&!a.playlist&&a.stop();a.playlist=a.playlists[b]};a._checkIds=function(b,c){var d="",e="";"undefined"!==typeof c.onSound&&(d=c.onSound);"undefined"!==typeof c.onPlayer&&(e=c.onPlayer);return d&&-1===b.indexOf(d)||e&&!a._inPlaylist(e,b)?!1:!0};a._checkIdsForElement=function(b,c){var d={};d.onSound=c.getAttribute("data-soundid");d.onPlayer=c.getAttribute("data-playerid");return a._checkIds(b,d)};a._updateTweens=function(b,c,d){for(var e=
b.length,g=0;g<e;g++){var j=b[g],l=j.getAttribute("data-tween");if((l=f.getJSON(l))&&"undefined"!==typeof l[c])for(var k=l[c].length,m=!1,h=!1,n=0;n<k;n++)h=l[c][n],a._checkIds(a.sound.id,h)&&(d>=h.startAt&&d<=h.endAt)&&(m=h.startVal+(h.endVal-h.startVal)/(h.endAt-h.startAt)*(d-h.startAt),m="px"==h.units?Math.floor(m):m.toFixed(2),j.style[h.name]=m+h.units)}};a._updateStyles=function(b,c){for(var d=b.length,e=0;e<d;e++){var g=b[e],f=g.getAttribute("data-styles");if((f=JSON.parse(f))&&"undefined"!==
typeof f[c])for(var l=f[c].length,k=0;k<l;k++)a._checkIds(a.sound.id,f[c][k])&&(g.style[f[c][k].name]=f[c][k].val)}};a._switchStylesForCollection=function(b,c,d){for(var e=b.length,g=0;g<e;g++)a._checkIdsForElement(a.sound.id,b[g])&&!f.styles.hasClass(a.sound.id,b[g],"inline")&&f.styles.swapClasses(b[g],c,d)};a._updateTimes=function(b){if(a.playlist)for(var c=document.querySelectorAll("div.cashmusic.soundplayer.playlist.playtime"),d=c.length,e=0;e<d;e++)if(a._checkIdsForElement(a.sound.id,c[e])){var g=
Math.floor(b/60),f=Math.floor(b-60*g);!isNaN(g)&&!isNaN(f)&&(f=(10>f?"0":"")+f,c[e].innerHTML=g+":"+f)}};a._updateTitle=function(){if(a.playlist)for(var b=document.querySelectorAll("div.cashmusic.soundplayer.playlist.nowplaying"),c=b.length,d=0;d<c;d++)a._checkIdsForElement(a.sound.id,b[d])&&(b[d].innerHTML=a.playlist.tracks[a.playlist.current-1].title)};a._formatPlaylist=function(a,c,d){a=a?a:{};a.id||(a.id=c?c:"pl---"+d);a.current=1;a.tracks=a.tracks?a.tracks:[];a._index=[];return a};a._formatTrack=
function(a,c){var d=f.getJSON(a.getAttribute("data-track")),d=d?d:{};d.url=d.url?d.url:a.href;d.title=d.title?d.title:a.innerText||a.textContent;d.id=c+d.url;return d};a._inPlaylist=function(b,c){return b?-1<a.playlists[b]._index.indexOf(c)?!0:!1:!1}})})();